# Generated by Django 5.2.16 on 2026-07-16 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scamcheck",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="scamcheck",
            name="safe_browsing_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scamcheck",
            name="url_checked",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name="scamcheck",
            index=models.Index(
                fields=["user", "-created_at"], name="chatbot_sca_user_id_c74346_idx"
            ),
        ),
    ]
